### PR TITLE
WIP Reimplement secret support

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description
- Pull secret support code from the faas gateway

## Motivation and Context

This address the bug raised in openfaas/faas#460
- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by stefanprodan** [comment]
@LucasRoesler I think is safe to undo the `go dep` files and the vendor dir. I see no new dependencies needed by the secrets.

**Comment by LucasRoesler** [comment]
it adds the docker cli dependency for the `opts` package.  This allows parsing the secrets in the same way that the docker-cli is documented, which gives it a lot of flexibility

**Comment by alexellis** [comment]
Please could you rebase the PR without the additional `dep` folder items? It makes review too hard as the browser struggles.

**Comment by alexellis** [comment]
Shame to have to take 1k new files just to have a helper function from the Docker CLI too :-/

**Comment by alexellis** [comment]
Also as stated previously this PR needs to be against my PR branch `swarm_breakout` and not against master.

**Comment by LucasRoesler** [comment]
should the gitignore include the vendor folder then?

**Comment by LucasRoesler** [comment]
I just rewrote the commit without the additions to the vendor folder

**Comment by LucasRoesler** [comment]
Looks like we are not rebuilding the vendor dir in travis, so it will fail without it.

**Comment by alexellis** [comment]
I know thank you 👍

**Pull request merged**
