### PR TITLE
Vendor with dep

### PR DESCRIPTION
**Pull request by stefanprodan**
## Description
Vendoring with dep

## Motivation and Context
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

See https://github.com/openfaas/faas/pull/460

## How Has This Been Tested?
Should be included in https://github.com/openfaas/faas/pull/460 testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by stefanprodan** [comment]
I can't reproduce the build error, running `make` locally it works...

**Comment by stefanprodan** [comment]
@alexellis there was an `openfaas-provider` orphan git submodule that was crashing the build. After half a day it finally works 😱

**Comment by alexellis** [comment]
Very well done.. 👍 

This PR has 4 commits and `+1,116,852` additions of code. Can we `rm` the vendor directory and resubmit with the Gopkg* changes only in a single squashed commit? Vendored deps can go up subsequently.

**Comment by alexellis** [comment]
Code taken and source history reset in master.

**Pull request closed without merging**
