### PR TITLE
[WIP] Moved to alpine and golang 1.11

### PR DESCRIPTION
**Pull request by auyer**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
- I built the new image and pushed it to a local Docker registry.
- I modified the `docker-compose.yml ` file from the [faas repository](https://raw.githubusercontent.com/openfaas/faas/master/docker-compose.yml) as such:
```
...
 # Docker Swarm provider
    faas-swarm:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        image:  localhost:5000/faas-swarm
        networks:
            - functions
...
```
- I ran  `./deploy_stack.sh --no-auth`
- Deployed a few private functions and tested them `faas-cli deploy -f divide.yml`
- Checked that the correct image was running:
```
8f990816e72c        localhost:5000/faas-swarm:latest   "./faas-swarm"           13 minutes ago      Up 13 minutes             8080/tcp
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, I explained on the previous PR that this needs to be 1.10, not 1.11 for Golang.

Alex

**Comment by alexellis** [comment]
Derek close: invalid

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
I appreciate the keenness but attention to detail is really important too. I've bumped up this repo to Alpine 3.8 for runtime and the latest acceptable Golang version already and referenced it on the tracking issue on the faas repo (I've sent a link in the other issue - please see what is approved)

Alex

**Comment by auyer** [comment]
Sorry for leaving it as WIP. I had to leave work in a hurry, and accidently created the PR instead of leaving as a draft. @alexellis 

My [TravisCI](https://travis-ci.org/auyer/faas-swarm/builds/435870828) tests show the ploblem was solved by adding gcc and libc-dev to the Dockerfile. Will propose this change in a new issue now.

**Pull request closed without merging**
