### PR TITLE
Move secrets mount path to /var/openfaas/secrets

### PR DESCRIPTION
**Pull request by LucasRoesler**
- change the secret configuration string spec to mount secrets in
/var/openfaas/secrets

## Description

Using a simple string format, this changes uses the docker cli parsing options to set the secret target to be in `/var/openfaas/secrets`.

This change also moves the secrets related methods (`makeSecretsArray`) to a separate `secrets.go` file to mimic the structure in the Kubernetes projects. Hopefully, this makes it easier to track changes across the projects.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
This change will ensure that the secrets required for the function business logic do not interfere with standard locations that other systems may want to modify.

This also ensures a consistent experience for function deployment across
swarm and k8s

Implements openfaas/faas#692
Relates to openfaas/faas-netes#188

## How Has This Been Tested?

I have tested this locally in Docker Swarm with a modified version of the [ApiKeyProtected-Secrets](https://github.com/openfaas/faas/tree/master/sample-functions/ApiKeyProtected-Secrets) example function. An updated docker image is available for testing at [theaxer/faas-swarm](https://hub.docker.com/r/theaxer/faas-swarm/)

I have not written any unit tests for this yet, because the method currently calls to the swarm api, so I need to research how to mock that interaction first. 

Changes will need to be made to the documentation and example functions in the [openfaas/faas](https://github.com/openfaas/faas) repo.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@LucasRoesler I'm eager to get this merged and released so we can update the docs.

Please could you work with one or two people to validate this change before I merge/release?

Perhaps @rgee0 @BurtonR or @ericstoekl ?

**Comment by BurtonR** [comment]
I can run through a couple of scenarios to try this out this evening. I'll post my results here as soon as it's complete.

**Comment by alexellis** [comment]
Thank you @BurtonR, that'd be great.

**Comment by BurtonR** [comment]
Apologies for the delay...

Tested this out on a local swarm and verified it works as expected :100: 
```
burtonr@pop-os:~/code/faas$ docker exec -it mv-secret.1.gdi7q2z8rw7g4hgynqrn2c873 /bin/sh
~ $ cat /var/openfaas/secrets/sauce 
awesomeness
```
Verified by including the secret both ways
`faas deploy -f mv-secret.yml --secret sauce`

and with the `yml` definition

```
functions:
  mv-secret:
    lang: node
    handler: ./mv-secret
    image: mv-secret
    secrets:
      - sauce
```

**Comment by alexellis** [comment]
Thank you Burton :+1:

**Comment by alexellis** [comment]
We now need to update the compose file to point at the latest release version.

**Pull request merged**
