### PR TITLE
Added capability to limit resources by CPU

### PR DESCRIPTION
**Pull request by nicholasjackson**
Signed-off-by: nicholasjackson <jackson.nic@gmail.com>

## How Has This Been Tested?
Other than unit testing and checking the code builds it has not been tested as I do not have access to a swarm cluster.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you @nicholasjackson !

**Comment by nicholasjackson** [comment]
If you need help testing, I can spin up a swarm cluster on azure later on in the week so I can deploy things.

**Comment by alexellis** [comment]
Hi @nicholasjackson thanks for adding these commits.

Full testing is required for a merge. I noticed you mentioned you have no access to Docker Swarm? The easiest way to test this is to install Docker on any Linux host and type in `docker swarm init` - that's all that is required.

> Other than unit testing and checking the code builds it has not been tested as I do not have access to a swarm cluster.

Please could you revisit the manual/exploratory testing for this PR? In addition to that - what if you pass an invalid value that cannot be parsed or is too or negative?

**Comment by alexellis** [comment]
@nicholasjackson this pull request has now been left inactive for over a month without testing and needs a re-base. What would you like me to do with it? Are you planning on completing the end-to-end testing with Docker Swarm?

This can be done in 5-10 minutes with https://play-with-docker.com

@BurtonR @ericstoekl are either of you willing to help me close this issue out by doing a re-base and testing? You may need to submit a new PR with Nic's commits.

**Comment by alexellis** [comment]
I've manually applied the commits to master and tried to test with the values given in the unit tests.. I got this:

> Unexpected status: 400, message: Deployment error: Error response from daemon: rpc error: code = InvalidArgument desc = invalid memory value -1: Must be at least 4MiB


> Unexpected status: 400, message: Deployment error: Error response from daemon: rpc error: code = InvalidArgument desc = invalid cpu value 1e-07: Must be at least 0.001

**Comment by alexellis** [comment]
Basic testing has shown that the current change makes CPU required if memory is given and visa-versa. I'm going to pick the changes up in a follow-up PR and do some more testing offline.

**Pull request closed without merging**
